name: Build Tests

on:
  workflow_dispatch:
    inputs:
      test_python_version:
        description: 'Python version to test with'
        required: true
        default: '3.12'
        type: choice
        options:
            - '3.12'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ github.event.inputs.test_python_version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ github.event.inputs.test_python_version }}
    
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python -
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    
    - name: Install dependencies
      run: |
        poetry install
    
    - name: Lint with ruff
      run: |
        poetry run python -m pip install ruff
        poetry run ruff check .
        
    - name: Format check with ruff
      run: |
        poetry run ruff format --check .
    
    - name: Test with pytest
      run: |
        poetry run pytest